# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS-Demos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOS-Demos

  pod 'Alamofire'
  pod 'Moya'
  
  pod 'PromisesSwift'
  
  pod 'R.swift'
  
  # RxSwift
  # https://github.com/ReactiveX/RxSwift
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxOptional'
  pod 'Moya/RxSwift'
  
end
